# Generated by Django 5.2.16 on 2026-08-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('hr_email', models.EmailField(max_length=254)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
